import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const ACCOUNT='0x1111111111111111111111111111111111111111';
function sharedPage({admin=true,round=null}={}){
 const dom=new JSDOM(fs.readFileSync('dist/index.html','utf8'),{url:'https://capital.test/#community',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;const state={admin,rounds:round?[round]:[],error:false,calls:[],signed:0},registered=[];
 w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.AbortSignal=AbortSignal;
 w.CapitalWallet={getAccount:()=>ACCOUNT,signBallot:async()=>{state.signed++;return 'test-signature';}};Object.defineProperty(w.document,'modelContext',{value:{registerTool:tool=>registered.push(tool)}});
 w.fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):undefined;state.calls.push({url,body,method:options.method});if(state.error)return new Response(JSON.stringify({error:'Database unavailable'}),{status:503});let data;
 if(url==='/api/voting/session')data={isAdmin:state.admin,signedIn:true,networks:{46630:{name:'Robinhood Chain Testnet',explorer:'https://explorer.testnet.chain.robinhood.com',testnet:true}}};
 else if(url==='/api/voting/rounds'&&!body)data={rounds:state.rounds};
 else if(url==='/api/voting/rounds'&&body){const r={id:'r-created',revision:1,version:1,status:'draft',payload:body,results:null};state.rounds.push(r);data={round:r};}
 else if(url.includes('/challenge'))data={challengeId:'nonce',typedData:{message:{wallet:ACCOUNT}}};
 else if(url.includes('/ballot')){const r=state.rounds[0];r.myBallot={id:'receipt-1',wallet:ACCOUNT,candidate:'animoca-brands',accepted_at:1,sequence:1};r.results.wallets=1;data={receipt:{id:'receipt-1',acceptedAt:1}};}
 else {const id=url.split('/').at(-1).split('?')[0];data={round:state.rounds.find(r=>r.id===id)};}
 return new Response(JSON.stringify(data),{status:200});};
 w.eval(['opportunities','app','community'].map(n=>fs.readFileSync(`dist/${n}.js`,'utf8')).join('\n'));
 const q=s=>w.document.querySelector(s),all=s=>[...w.document.querySelectorAll(s)],flush=async()=>{for(let i=0;i<6;i++)await new Promise(resolve=>setTimeout(resolve,0));};return {w,state,q,all,flush,registered,close:()=>w.close()};
}
const sharedRound=()=>({id:'r-open',revision:1,version:2,status:'open',proposalHash:'0xabc',snapshot:{number:12,time:1,hash:'0xdef'},payload:{title:'Technology',notes:'Reviewed shortlist',token:ACCOUNT,chainId:46630,rule:'token-weighted',minimum:'1',decimals:18,symbol:'CAP',opensAt:1,closesAt:2000000000,candidates:[{id:'miso-robotics',name:'Miso Robotics',image:'/assets/miso-robotics.webp',platform:'Republic',security:'Common stock',terms:'Current terms',source:'https://republic.com/miso-robotics',documents:'https://sec.gov/test',reviewed:true,checkedAt:1,status:'open'},{id:'animoca-brands',name:'Animoca Brands',image:'/assets/animoca-brands.jpg',platform:'Republic',security:'Beneficial interest',terms:'Current secondary terms',source:'https://republic.com/animoca',documents:'https://republic.com/animoca/docs',reviewed:true,checkedAt:1,status:'secondary'}]},results:{wallets:0,candidates:[{id:'miso-robotics',weight:'0',percent:0},{id:'animoca-brands',weight:'0',percent:0}]}});
test('shared empty state does not create fake votes and only administrators can start drafts',async()=>{for(const admin of [true,false]){const p=sharedPage({admin});try{await p.flush();assert.equal(p.q('#new-round').hidden,!admin);assert.equal(p.all('[data-shared-vote]').length,0);assert.match(p.q('#voting-empty').textContent,/No published/);const read=p.registered.find(t=>t.name==='capital_read_voting_rounds');assert.deepEqual(JSON.parse(JSON.stringify(await read.execute({}))),{rounds:[]});if(!admin)await assert.rejects(()=>p.registered.find(t=>t.name==='capital_start_round_draft').execute({}),/Administrator access/);}finally{p.close();}}});
test('draft form submits shared data with explicit unverified offering reviews',async()=>{const p=sharedPage();try{await p.flush();await p.registered.find(t=>t.name==='capital_start_round_draft').execute({});p.q('#round-name').value='My shortlist';for(const id of ['miso-robotics','animoca-brands'])p.q(`[name=candidate][value="${id}"]`).click();p.q('#round-form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await p.flush();const post=p.state.calls.find(c=>c.url==='/api/voting/rounds'&&c.body);assert.equal(post.body.title,'My shortlist');assert(post.body.candidates.every(c=>!c.reviewed&&c.status==='unverified'));assert.equal(p.q('#round-editor').open,false);assert.match(p.q('#rounds-feedback').textContent,/shared storage/);assert.equal(p.state.signed,0);}finally{p.close();}});
test('holder UI signs before submission and displays the accepted current ballot receipt',async()=>{const p=sharedPage({admin:false,round:sharedRound()});try{await p.flush();p.q('[data-shared-vote="animoca-brands"]').click();await p.flush();assert.equal(p.state.signed,1);const posts=p.state.calls.filter(c=>c.body);assert(posts[0].url.endsWith('/challenge'));assert(posts[1].url.endsWith('/ballot'));assert.match(p.q('#community-round-summary').textContent,/receipt-1/);assert(p.q('[data-shared-vote="animoca-brands"]').disabled);assert.match(p.q('#community-feedback').textContent,/Vote accepted/);}finally{p.close();}});
test('failed refresh labels stale data and disables voting instead of substituting zero results',async()=>{const r=sharedRound();r.results.wallets=9;const p=sharedPage({admin:false,round:r});try{await p.flush();p.state.error=true;p.q('#refresh-voting').click();await p.flush();assert.match(p.q('#community-feedback').textContent,/could not be refreshed/);assert(p.all('[data-shared-vote]').every(b=>b.disabled));assert.match(p.q('#community-round-summary').textContent,/9/);}finally{p.close();}});
