import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {localDatabase,migrate} from '../scripts/local-db.mjs';
const built=await build({entryPoints:['server/worker.js'],write:false,bundle:true,platform:'node',format:'esm',target:['node24']});const {createApp}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const origin='https://capital.test';
function setup(){const db=localDatabase();migrate(db);const app=createApp(),env={DB:db,CAPITAL_SITE_ORIGIN:origin,CAPITAL_ADMIN_EMAIL:'owner@capital.test'};const call=async(path,body,{user='private-member-a',requestOrigin=origin,method=body===undefined?'GET':'POST'}={})=>{const response=await app.fetch(new Request(origin+'/api/forum/'+path,{method,headers:{'content-type':'application/json',origin:requestOrigin,...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user==='owner'?'owner@capital.test':user+'@capital.test'}:{})},body:body===undefined?undefined:JSON.stringify(body)}),env,{});return {status:response.status,data:await response.json()};};return {db,call,close:()=>db.sqlite.close()};}
const message=(body='A business worth discussing',replyTo=null)=>({requestId:crypto.randomUUID(),body,replyTo});
const pick=(companyId,expectedVersion=0)=>({companyId,expectedVersion});

test('company interest is shared, replaceable, removable and separate from formal votes',async()=>{const s=setup();try{
 const empty=(await s.call('company-interest')).data;assert.equal(empty.totalPicks,0);assert.ok(empty.companies.every(c=>c.supporters===0&&c.rank===null));
 let a=await s.call('company-interest',pick('animoca-brands'));assert.equal(a.status,200);assert.equal(a.data.selectedCompany,'animoca-brands');assert.equal(a.data.version,1);
 const b=await s.call('company-interest',pick('atombeam'),{user:'private-member-b'});assert.equal(b.data.totalPicks,2);assert.deepEqual(b.data.companies.slice(0,2).map(c=>c.rank),[1,1]);
 a=await s.call('company-interest',pick('atombeam',1));assert.equal(a.data.companies[0].id,'atombeam');assert.equal(a.data.companies[0].supporters,2);assert.equal(a.data.companies.find(c=>c.id==='animoca-brands').supporters,0);
 assert.equal((await s.call('company-interest',pick('atombeam',1))).data.totalPicks,2);
 a=await s.call('company-interest',pick(null,2));assert.equal(a.data.totalPicks,1);assert.equal(a.data.selectedCompany,null);assert.equal((await s.call('company-interest',pick(null,2))).data.version,3);
 assert.equal((await s.call('company-interest',undefined,{user:'private-member-b'})).data.selectedCompany,'atombeam');assert.doesNotMatch(JSON.stringify(a.data),/private-member|@capital|user_id/);
 for(const table of ['capital_votes','capital_rounds','capital_messages'])assert.equal(s.db.sqlite.prepare(`SELECT COUNT(*) AS n FROM ${table}`).get().n,0);
 }finally{s.close();}});

test('company picks require trusted identity, origin, valid directory entries and strict input',async()=>{const s=setup();try{
 for(const body of [null,[],{},pick('missing'),pick(1),pick('atombeam',-1),pick('atombeam',1.5),{...pick('atombeam'),userId:'somebody-else'}])assert.equal((await s.call('company-interest',body)).status,400);
 assert.equal((await s.call('company-interest',undefined,{user:''})).status,401);assert.equal((await s.call('company-interest',pick('atombeam'),{user:''})).status,401);assert.equal((await s.call('company-interest',pick('atombeam'),{requestOrigin:'https://evil.test'})).status,403);
 assert.equal((await s.call('company-interest',pick('atombeam',99))).status,409);assert.equal(s.db.sqlite.prepare('SELECT COUNT(*) AS n FROM capital_company_interest').get().n,0);
 s.db.sqlite.prepare('INSERT INTO capital_company_interest VALUES(?,?,?,?)').run('private-member-a','obsolete-company',4,1);const removed=(await s.call('company-interest')).data;assert.equal(removed.totalPicks,0);assert.equal(removed.selectedCompany,null);assert.equal(removed.version,4);
 assert.equal((await s.call('company-interest',pick('atombeam',4))).data.totalPicks,1);
 }finally{s.close();}});

test('concurrent and stale picks cannot multiply support or resurrect a removed choice',async()=>{const s=setup();try{
 const results=await Promise.all(['atombeam','animoca-brands','miso-robotics'].map(id=>s.call('company-interest',pick(id))));assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(results.filter(r=>r.status===409).length,2);
 const current=(await s.call('company-interest')).data;assert.equal(current.totalPicks,1);assert.equal(current.version,1);assert.equal(s.db.sqlite.prepare('SELECT COUNT(*) AS n FROM capital_company_interest').get().n,1);
 await s.call('company-interest',pick(null,1));assert.equal((await s.call('company-interest',pick(current.selectedCompany,0))).status,409);assert.equal((await s.call('company-interest')).data.totalPicks,0);
 }finally{s.close();}});

test('failed preference writes preserve the confirmed choice and indexed counts',async()=>{const s=setup();try{
 await s.call('company-interest',pick('atombeam'));s.db.sqlite.exec("CREATE TRIGGER fail_interest BEFORE UPDATE ON capital_company_interest BEGIN SELECT RAISE(ABORT,'injected failure'); END;");
 assert.equal((await s.call('company-interest',pick('animoca-brands',1))).status,503);assert.equal((await s.call('company-interest')).data.selectedCompany,'atombeam');s.db.sqlite.exec('DROP TRIGGER fail_interest');assert.equal((await s.call('company-interest',pick('animoca-brands',1))).data.selectedCompany,'animoca-brands');
 s.db.sqlite.exec('PRAGMA optimize');const plan=s.db.sqlite.prepare('EXPLAIN QUERY PLAN SELECT company_id,COUNT(*) FROM capital_company_interest GROUP BY company_id').all();assert.match(JSON.stringify(plan),/idx_capital_interest_company/);
 }finally{s.close();}});
test('members share durable messages and replies without exposing private identity',async()=>{const s=setup();try{const a=await s.call('messages',message());assert.equal(a.status,201);const b=await s.call('messages',message('I will review the offering',a.data.message.id),{user:'private-member-b'});assert.equal(b.status,201);const list=await s.call('messages');assert.equal(list.data.messages.length,2);assert.equal(list.data.messages[0].replyTo.id,a.data.message.id);assert.notEqual(list.data.messages[0].author,list.data.messages[1].author);assert.equal(list.data.messages[1].isMine,true);assert.doesNotMatch(JSON.stringify(list),/private-member|@capital\.test|user_id/);assert.equal((await s.call('messages',undefined,{user:''})).status,401);assert.equal((await s.call('messages',message(),{user:''})).status,401);assert.equal((await s.call('messages',message(),{requestOrigin:'https://evil.test'})).status,403);}finally{s.close();}});
test('atomic rate limit accepts five concurrent posts and retries remain idempotent',async()=>{const s=setup();try{const inputs=Array.from({length:7},(_,i)=>message('Post '+i));const results=await Promise.all(inputs.map(m=>s.call('messages',m)));assert.equal(results.filter(r=>r.status===201).length,5);assert.equal(results.filter(r=>r.status===429).length,2);const accepted=inputs[results.findIndex(r=>r.status===201)];assert.equal((await s.call('messages',accepted)).data.duplicate,true);assert.equal((await s.call('messages',{...accepted,body:'Changed'})).status,409);assert.equal((await s.call('messages',accepted,{user:'second-member'})).status,201);assert.equal((await s.call('messages')).data.messages.length,6);}finally{s.close();}});
test('invalid input and unavailable reply targets fail without storing a post',async()=>{const s=setup();try{for(const body of [null,[],{},message(''),message('x'.repeat(2001)),message(42),{...message(),requestId:'wrong'},{...message(),replyTo:'1'}])assert.equal((await s.call('messages',body)).status,400);assert.equal((await s.call('messages',message('Reply',999))).status,409);assert.equal((await s.call('messages')).data.messages.length,0);const post=await s.call('messages',message());await s.call(`messages/${post.data.message.id}/visibility`,{hidden:true});assert.equal((await s.call('messages',message('Reply',post.data.message.id))).status,409);}finally{s.close();}});
test('author removal can be restored but administrator moderation cannot be bypassed',async()=>{const s=setup();try{await s.call('session',undefined,{user:'owner'});const r=await s.call('messages',message('Remove then restore'));const route=`messages/${r.data.message.id}/visibility`;assert.equal((await s.call(route,{hidden:true},{user:'stranger'})).status,403);assert.equal((await s.call(route,{hidden:true})).data.message.body,'');assert.equal((await s.call(route,{hidden:false})).data.message.body,'Remove then restore');await s.call(route,{hidden:true});await s.call(route,{hidden:true},{user:'owner'});assert.equal((await s.call(route,{hidden:false})).status,403);assert.equal((await s.call(route,{hidden:false},{user:'owner'})).data.message.hidden,false);await Promise.all([s.call(route,{hidden:true}),s.call(route,{hidden:true},{user:'owner'})]);assert.equal((await s.call(route,{hidden:false})).status,403);}finally{s.close();}});
test('integer cursor pages equal timestamps without gaps and queries use intended indexes',async()=>{const s=setup();try{for(let i=0;i<65;i++)s.db.sqlite.prepare('INSERT INTO capital_messages(user_id,request_id,body,created_at) VALUES(?,?,?,?)').run('fixture',String(i),'Message '+i,123);const first=await s.call('messages'),second=await s.call('messages?before='+first.data.nextBefore);assert.equal(first.data.messages.length,50);assert.equal(first.data.hasMore,true);assert.equal(second.data.messages.length,15);assert.equal(second.data.hasMore,false);assert.equal(new Set([...first.data.messages,...second.data.messages].map(m=>m.id)).size,65);s.db.sqlite.exec('PRAGMA optimize');const plan=s.db.sqlite.prepare('EXPLAIN QUERY PLAN SELECT COUNT(*) FROM capital_messages WHERE user_id=? AND created_at>?').all('fixture',0);assert.match(JSON.stringify(plan),/idx_capital_message_user_time/);assert.equal((await s.call('messages?before=-1')).status,400);}finally{s.close();}});
test('failed storage preserves idempotent request and does not claim a saved message',async()=>{const s=setup();try{const body=message('Keep this draft');s.db.sqlite.exec("CREATE TRIGGER fail_message BEFORE INSERT ON capital_messages BEGIN SELECT RAISE(ABORT,'injected failure'); END;");assert.equal((await s.call('messages',body)).status,503);assert.equal((await s.call('messages')).data.messages.length,0);s.db.sqlite.exec('DROP TRIGGER fail_message');assert.equal((await s.call('messages',body)).status,201);assert.equal((await s.call('messages',body)).data.duplicate,true);}finally{s.close();}});
