import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {build} from 'esbuild';import {Wallet,parseUnits} from 'ethers';import {localDatabase,migrate} from '../scripts/local-db.mjs';import {now,hash,tally} from '../server/voting-model.js';
const bundled=await build({entryPoints:['server/worker.js'],write:false,bundle:true,platform:'node',format:'esm',target:['node24']});const {createApp}=await import('data:text/javascript;base64,'+Buffer.from(bundled.outputFiles[0].text).toString('base64'));
const A=Wallet.createRandom(),B=Wallet.createRandom(),C=Wallet.createRandom();const weights={[A.address.toLowerCase()]:(2n**100n).toString(),[B.address.toLowerCase()]:'3000000000000000000'};const origin='https://capital.test',blockHash='0x'+'ab'.repeat(32);
const input=()=>({title:'Test voting round',notes:'A local integration test.',target:'1000',chainId:46630,token:Wallet.createRandom().address,rule:'token-weighted',minimum:'1',opensAt:now()-5,closesAt:now()+3600,candidates:[{id:'miso-robotics',security:'Common stock',terms:'Verified test terms',source:'https://republic.com/miso-robotics',documents:'https://www.sec.gov/test',status:'open',checkedAt:now(),reviewed:true},{id:'animoca-brands',security:'Beneficial interest',terms:'Verified test secondary terms',source:'https://republic.com/animoca',documents:'https://republic.com/animoca/documents',status:'secondary',checkedAt:now(),reviewed:true}]});
function setup(){const db=localDatabase();migrate(db);const env={DB:db,CAPITAL_ADMIN_EMAIL:'owner@capital.test',CAPITAL_SITE_ORIGIN:origin};let failures=false;
 const app=createApp({verifyToken:async()=>({decimals:18,symbol:'CAP'}),openingSnapshot:async()=>({number:123,hash:blockHash,time:now()-5}),snapshotWeight:async(_env,_p,_r,wallet)=>{if(failures)throw Error('Simulated RPC failure');if(!weights[wallet])throw Object.assign(Error('Not eligible'),{status:403});return weights[wallet];}});
 const call=async(path,body,{user='owner',email=user==='owner'?'owner@capital.test':user+'@capital.test',method=body?'POST':'GET',requestOrigin=origin}={})=>{const req=new Request(origin+'/api/voting/'+path,{method,headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':email}:{}),origin:requestOrigin,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const res=await app.fetch(req,env,{});return {status:res.status,data:await res.json()};};
 const create=async()=>{const r=await call('rounds',input());assert.equal(r.status,201);return r.data.round;};
 const publish=async r=>{const result=await call(`rounds/${r.id}/publish`,{version:r.version});assert.equal(result.status,200,JSON.stringify(result));await call('rounds/'+r.id);return result.data.round;};
 const challenge=async(r,wallet,candidate='miso-robotics',user='member')=>{const r0=await call(`rounds/${r.id}/challenge`,{wallet:wallet.address,candidate},{user});assert.equal(r0.status,200,JSON.stringify(r0));const {typedData,challengeId}=r0.data;return {challengeId,signature:await wallet.signTypedData(typedData.domain,typedData.types,typedData.message),typedData};};
 const vote=(r,c,user='member')=>call(`rounds/${r.id}/ballot`,c,{user});return {db,call,create,publish,challenge,vote,fail(value){failures=value;},close(){db.sqlite.close();}};
}
test('admin is pinned to the trusted Sites identity; drafts are private and CSRF is rejected',async()=>{const s=setup();try{assert.equal((await s.call('session')).data.isAdmin,true);const r=await s.create();assert.equal((await s.call('session',undefined,{user:'attacker',email:'owner@capital.test'})).data.isAdmin,false);assert.equal((await s.call('rounds',input(),{user:'member'})).status,403);assert.equal((await s.call('rounds',undefined,{user:'member'})).data.rounds.length,0);assert.equal((await s.call('rounds/'+r.id,undefined,{user:'member'})).status,404);assert.equal((await s.call('rounds',input(),{requestOrigin:'https://attacker.test'})).status,403);assert.equal((await s.call('rounds',input(),{user:''})).status,401);}finally{s.close();}});
test('drafts save idempotently and published rounds freeze terms and verified metadata',async()=>{const s=setup();try{const data={...input(),requestId:crypto.randomUUID()};const a=await s.call('rounds',data),b=await s.call('rounds',data);assert.equal(a.data.round.id,b.data.round.id);let r=a.data.round;r=await s.publish(r);assert(r.proposalHash);assert.equal(r.payload.symbol,'CAP');assert.equal((await s.call('rounds/'+r.id,{...input(),version:r.version},{method:'PUT'})).status,409);const incomplete=await s.call('rounds',{...input(),token:'',rule:''});assert.equal((await s.call(`rounds/${incomplete.data.round.id}/publish`,{version:1})).status,400);}finally{s.close();}});
test('signed votes are shared, precision-safe, replaceable and retried without duplicate counts',async()=>{const s=setup();try{const r=await s.publish(await s.create()),a=await s.challenge(r,A),b=await s.challenge(r,B,'animoca-brands','member-b');assert.equal((await s.vote(r,a)).status,201);assert.equal((await s.vote(r,a)).data.duplicate,true);assert.equal((await s.vote(r,b,'member-b')).status,201);let result=(await s.call('rounds/'+r.id+'?wallet='+A.address)).data.round;assert.equal(result.results.totalWeight,(BigInt(weights[A.address.toLowerCase()])+BigInt(weights[B.address.toLowerCase()])).toString());assert.equal(result.myBallot.candidate,'miso-robotics');const replacement=await s.challenge(r,A,'animoca-brands');assert.equal((await s.vote(r,replacement)).status,201);result=(await s.call('rounds/'+r.id)).data.round;assert.equal(result.results.wallets,2);assert.equal(result.results.candidates[0].weight,'0');assert.equal(result.results.candidates[1].percent,100);const history=(await s.call(`rounds/${r.id}/audit`)).data;assert.equal(history.receipts.length,3);assert(history.receipts.every(v=>v.signature&&v.typedData));}finally{s.close();}});
test('forged signatures, different users, stale sequences and expired ballots cannot be accepted',async()=>{const s=setup();try{const r=await s.publish(await s.create()),old=await s.challenge(r,A),next=await s.challenge(r,A,'animoca-brands');const forged={...old,signature:await B.signTypedData(old.typedData.domain,old.typedData.types,old.typedData.message)};assert.equal((await s.vote(r,forged)).status,403);assert.equal((await s.vote(r,old,'another-user')).status,404);assert.equal((await s.vote(r,next)).status,201);assert.equal((await s.vote(r,old)).status,409);const expired=await s.challenge(r,A);s.db.sqlite.prepare('UPDATE capital_vote_challenges SET expires_at=? WHERE id=?').run(now()-1,expired.challengeId);assert.equal((await s.vote(r,expired)).status,409);assert.equal((await s.call(`rounds/${r.id}/challenge`,{wallet:C.address,candidate:'miso-robotics'},{user:'member'})).status,403);}finally{s.close();}});
test('concurrent votes accept one sequence; closing locks final results and retains idempotent receipts',async()=>{const s=setup();try{const r=await s.publish(await s.create()),a=await s.challenge(r,A),b=await s.challenge(r,A,'animoca-brands');const results=await Promise.all([s.vote(r,a),s.vote(r,b)]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);const accepted=results[0].status===201?a:b;const late=await s.challenge(r,A,'animoca-brands');s.db.sqlite.prepare('UPDATE capital_rounds SET closes_at=? WHERE id=?').run(now()-1,r.id);assert.equal((await s.vote(r,late)).status,409);assert.equal((await s.vote(r,accepted)).status,200);const final1=(await s.call('rounds/'+r.id)).data.round,final2=(await s.call('rounds/'+r.id)).data.round;assert.equal(final1.status,'closed');assert.equal(final1.results.final,true);assert(final1.results.digest);assert.deepEqual(final1.results,final2.results);assert.equal(final1.results.wallets,1);}finally{s.close();}});
test('revisions stop old ballots and require fresh votes without mutating the old decision',async()=>{const s=setup();try{const r=await s.publish(await s.create()),vote=await s.challenge(r,A);await s.vote(r,vote);const result=await s.call(`rounds/${r.id}/revise`,{version:r.version,reason:'The provider changed material offering terms.'});assert.equal(result.status,201);assert.equal(result.data.round.revision,2);assert.equal(result.data.round.results,null);assert(result.data.round.payload.candidates.every(c=>!c.reviewed));assert.equal((await s.call('rounds/'+r.id)).data.round.status,'paused');assert.equal((await s.call(`rounds/${r.id}/challenge`,{wallet:B.address,candidate:'animoca-brands'},{user:'member-b'})).status,409);assert.equal((await s.call(`rounds/${r.id}/audit`)).data.receipts.length,1);}finally{s.close();}});
test('RPC and SQL failures do not record a vote or substitute a zero balance',async()=>{const s=setup();try{const r=await s.publish(await s.create()),vote=await s.challenge(r,A);s.fail(true);assert.equal((await s.vote(r,vote)).status,503);assert.equal((await s.call('rounds/'+r.id)).data.round.results.wallets,0);s.fail(false);s.db.sqlite.exec("CREATE TRIGGER fail_ballot BEFORE INSERT ON capital_votes BEGIN SELECT RAISE(ABORT,'injected failure'); END;");assert.equal((await s.vote(r,vote)).status,503);assert.equal(s.db.sqlite.prepare('SELECT COUNT(*) AS n FROM capital_votes').get().n,0);s.db.sqlite.exec('DROP TRIGGER fail_ballot');assert.equal((await s.vote(r,vote)).status,201);}finally{s.close();}});
