import {test} from 'node:test';import assert from 'node:assert/strict';import {Wallet} from 'ethers';import {openingSnapshot,snapshotWeight,verifyToken} from '../server/snapshot.js';import {tokenInterface,now} from '../server/voting-model.js';
const wallet=Wallet.createRandom().address,token=Wallet.createRandom().address,base=now()-1000;const blockHash=n=>'0x'+n.toString(16).padStart(64,'0');
function fixture(){const original=globalThis.fetch,calls=[];let wrongChain=false,reorg=false,unavailable=false,head=40;const timestamp=n=>base+(n===10||n===11?120:n*12);globalThis.fetch=async(_url,request)=>{const {method,params}=JSON.parse(request.body);calls.push({method,params});if(unavailable)throw Error('Offline');let result;
 if(method==='eth_chainId')result=wrongChain?'0x1':'0xb626';
 else if(method==='eth_getBlockByNumber'){const n=params[0]==='finalized'?head:Number(BigInt(params[0]));result={number:'0x'+n.toString(16),hash:reorg?'0x'+'ff'.repeat(32):blockHash(n),timestamp:'0x'+timestamp(n).toString(16)};}
 else if(method==='eth_getCode')result='0x6000';
 else if(method==='eth_call'){const parsed=tokenInterface.parseTransaction({data:params[0].data});const value=parsed.name==='decimals'?18:parsed.name==='symbol'?'CAP':parsed.name==='totalSupply'?10n**30n:params[1]==='0xb'?2n**100n:0n;result=tokenInterface.encodeFunctionResult(parsed.name,[value]);}
 return new Response(JSON.stringify({jsonrpc:'2.0',id:1,result}),{headers:{'content-type':'application/json'}});};return {calls,set(values){if('wrongChain'in values)wrongChain=values.wrongChain;if('reorg'in values)reorg=values.reorg;if('unavailable'in values)unavailable=values.unavailable;if('head'in values)head=values.head;},close(){globalThis.fetch=original;}};}
const p={chainId:46630,token,decimals:18,minimum:'1',rule:'token-weighted',opensAt:base+120};
test('snapshot selects the last block at opening and waits for a later finalized timestamp',async()=>{const f=fixture();try{assert.deepEqual(await openingSnapshot({},p),{number:11,hash:blockHash(11),time:base+120});f.set({head:11});await assert.rejects(()=>openingSnapshot({},p),/Waiting for the opening block/);}finally{f.close();}});
test('eligibility uses the historical snapshot and fails on reorg or RPC outage',async()=>{const f=fixture();try{const r={snapshot_number:11,snapshot_hash:blockHash(11)};assert.equal(await snapshotWeight({},p,r,wallet),(2n**100n).toString());assert(f.calls.filter(c=>c.method==='eth_call').every(c=>c.params[1]==='0xb'));assert.equal(await snapshotWeight({}, {...p,rule:'one-wallet'},r,wallet),'1');f.set({reorg:true});await assert.rejects(()=>snapshotWeight({},p,r,wallet),/canonical/);f.set({reorg:false,unavailable:true});await assert.rejects(()=>snapshotWeight({},p,r,wallet),/could not verify/);}finally{f.close();}});
test('token setup verifies finalized metadata and chain identity',async()=>{const f=fixture();try{assert.deepEqual(await verifyToken({},p),{decimals:18,symbol:'CAP'});f.set({wrongChain:true});await assert.rejects(()=>verifyToken({},p),/different network/);}finally{f.close();}});
