import {formatUnits,id as textHash} from 'ethers';
import {validateState,STORAGE_KEY} from './rounds-model.js';
const $=s=>document.querySelector(s),esc=window.MainstreetDirectory.escapeHtml,companies=window.MainstreetDirectory.opportunities;
let session=null,rounds=[],selected=null,filter='all',editing=null,requestId=null,busy=false,actionPending=null,auditOffset=0,auditRound=null,loadSequence=0;
const date=value=>value?new Date(value*1000).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'Not set';
const label={draft:'Draft',archived:'Archived',scheduled:'Scheduled',open:'Voting open',closed:'Closed',paused:'Paused','snapshot-pending':'Verifying opening snapshot'};
const wallet=()=>window.CapitalWallet?.getAccount()||null;
const amount=(value,p)=>p.rule==='one-wallet'?value:formatUnits(value,p.decimals??0);
const metric=(label,value)=>`<div><span>${esc(label)}</span><strong>${esc(String(value))}</strong></div>`;
const avatar=c=>`<img class="round-company-image" src="${esc(c.image)}" alt="" loading="lazy">`;
async function api(path,body,method='POST'){
 const response=await fetch('/api/voting/'+path,{method:body===undefined?'GET':method,credentials:'same-origin',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(60000)});
 let result;try{result=await response.json();}catch{throw Error('Shared voting could not be reached. Your input is still here.');}if(!response.ok)throw Error(result.error||'The request did not complete.');return result;
}
function feedback(message){$('#community-feedback').textContent=message;$('#rounds-feedback').textContent=message;}
function statusText(){return session?.preview?'Local preview · separate shared database':'Shared rounds · verified ballots';}
function renderList(){
 const active=rounds.filter(r=>['open','scheduled','snapshot-pending'].includes(r.status));$('#rounds-summary').innerHTML=metric('Published rounds',rounds.filter(r=>!['draft','archived'].includes(r.status)).length)+metric('Open for voting',rounds.filter(r=>r.status==='open').length)+metric('Closed rounds',rounds.filter(r=>r.status==='closed').length);
 const visible=rounds.filter(r=>filter==='all'||filter==='active'&&active.includes(r)||filter==='closed'&&r.status==='closed'||filter==='draft'&&['draft','archived'].includes(r.status));
 $('#rounds-count').textContent=`${visible.length} ${visible.length===1?'round':'rounds'}`;
 document.querySelectorAll('[data-round-filter]').forEach(e=>{e.setAttribute('aria-pressed',String(e.dataset.roundFilter===filter));if(e.dataset.roundFilter==='draft')e.hidden=!session?.isAdmin;});
 $('#new-round').hidden=!session?.isAdmin;$('#import-browser-drafts').hidden=!session?.isAdmin||!legacyDrafts().length;$('#round-admin-label').textContent=session?.isAdmin?'Administrator':'';
 $('#rounds-list').innerHTML=visible.length?visible.map(r=>{const p=r.payload;return `<article class="round-card"><div class="round-card-top"><span class="round-eyebrow">REVISION ${r.revision}</span><span class="round-state">${esc(label[r.status])}</span></div><h2>${esc(p.title)}</h2><p class="round-card-description">${esc(p.notes)}</p><div class="round-card-details"><div class="round-avatar-group">${p.candidates.slice(0,5).map(avatar).join('')}<span>${p.candidates.length} businesses</span></div><div class="round-target"><span>Planning target</span><strong>${p.target?'$'+esc(Number(p.target).toLocaleString('en-US')):'Not set'}</strong></div><div class="round-preference"><span>Voting closes</span><strong>${esc(date(p.closesAt))}</strong></div></div><div class="round-card-actions"><a class="button button-dark" href="#community/${esc(r.id)}">${r.status==='draft'?'Review draft':'View round'} ↗</a><div>${session?.isAdmin?adminActions(r):`<span class="community-footnote">${r.results?.wallets??0} accepted ballots</span>`}</div></div></article>`;}).join(''):`<div class="round-empty"><h2>${filter==='draft'?'No drafts yet':'No rounds here yet'}</h2><p>${session?.isAdmin?'Create a shortlist and review the terms before opening voting.':'The administrator will publish the next reviewed shortlist here.'}</p></div>`;
}
function adminActions(r){if(r.status==='draft')return `<button class="round-text-link" data-edit-round="${r.id}">Edit draft</button><button class="round-text-link" data-round-action="publish" data-round-id="${r.id}">Publish</button><button class="round-text-link" data-round-action="archive" data-round-id="${r.id}">Archive</button>`;if(r.status==='archived')return `<button class="round-text-link" data-round-action="archive" data-round-id="${r.id}">Restore</button>`;return `${['open','scheduled','snapshot-pending'].includes(r.status)?`<button class="round-text-link" data-round-action="pause" data-round-id="${r.id}">Pause voting</button>`:''}<button class="round-text-link" data-round-action="revise" data-round-id="${r.id}">New revision</button>`;}
function renderRound(snapshotError=null){
 const r=selected,p=r?.payload;$('#voting-empty').hidden=!!r;$('#voting-round-view').hidden=!r;
 if(!r){$('#voting-empty').innerHTML=`<h2>No published voting round yet</h2><p>${session?.isAdmin?'Create a round, review the businesses, and configure the holder voting rules.':'A reviewed shortlist will appear here when voting is scheduled.'}</p><a class="button button-light" href="#rounds">View investment rounds ↗</a>`;return;}
 $('#community-round').innerHTML=rounds.map(v=>`<option value="${v.id}" ${v.id===r.id?'selected':''}>${esc(v.payload.title)} · v${v.revision}</option>`).join('');$('#community-round-state').textContent=label[r.status];
 const mine=r.myBallot?.wallet===wallet()?.toLowerCase()?r.myBallot:null;const results=r.results,open=r.status==='open',rule=p.rule==='token-weighted'?'Token balance at opening':p.rule==='one-wallet'?'One eligible wallet · one vote':'Not configured';
 $('#community-round-summary').innerHTML=`<div class="round-overview"><div class="round-overview-heading"><div><span class="round-eyebrow">REVISION ${r.revision}${session?.networks[p.chainId]?.testnet?' · TESTNET':''}</span><h2>${esc(p.title)}</h2><p>${esc(p.notes)}</p></div>${session?.isAdmin?`<div class="voting-admin-actions">${adminActions(r)}</div>`:''}</div><div class="round-metrics">${metric('Accepted ballots',results?results.wallets:'Voting has not opened')}${metric('Voting closes',date(p.closesAt))}${metric('Voting rule',rule)}</div><details class="voting-rules"><summary>Terms, eligibility & snapshot</summary><dl><div><dt>Network</dt><dd>${esc(session?.networks[p.chainId]?.name||p.chainId)}</dd></div><div><dt>Token</dt><dd>${p.token?`<a target="_blank" rel="noopener noreferrer" href="${esc(session.networks[p.chainId].explorer)}/address/${p.token}">${esc(p.symbol||p.token)}</a>`:'Not configured'}</dd></div><div><dt>Minimum holding</dt><dd>${esc(p.minimum)} ${esc(p.symbol||'tokens')}</dd></div><div><dt>Opens</dt><dd>${esc(date(p.opensAt))}</dd></div><div><dt>Snapshot</dt><dd>${r.snapshot?`Block ${r.snapshot.number} · ${esc(date(r.snapshot.time))}`:'Fixed from the last finalized block at or before opening. Voting waits for verification.'}</dd></div><div><dt>Terms record hash</dt><dd>${esc(r.proposalHash||'Created at publication')}</dd></div>${results?.digest?`<div><dt>Final results digest</dt><dd>${esc(results.digest)}</dd></div>`:''}</dl></details>${mine?`<p class="community-footnote">Your current vote: <strong>${esc(p.candidates.find(c=>c.id===mine.candidate)?.name||mine.candidate)}</strong> · receipt ${esc(mine.id)} · ${esc(date(mine.accepted_at))}</p>`:''}${r.status==='draft'?'<p class="community-footnote">Draft only. Complete the token settings and review every offering before publishing.</p>':''}${snapshotError?`<p class="round-form-error">${esc(snapshotError)}</p>`:''}${r.status==='paused'?'<p class="community-footnote">Voting is paused. Previous ballots remain in the history. A new revision requires a fresh vote.</p>':''}${!session?.signedIn&&open?'<a class="button button-light" target="_top" href="/signin-with-chatgpt?return_to=%2F%23community">Sign in to vote</a>':''}</div>`;
 $('#community-candidates').innerHTML=p.candidates.map(c=>{const result=results?.candidates.find(v=>v.id===c.id),chosen=mine?.candidate===c.id;return `<article class="community-company ${chosen?'is-chosen':''}">${avatar(c)}<div class="community-company-info"><h3>${esc(c.name)}</h3><span class="community-company-meta">${esc(c.platform)} · ${esc(c.security)}</span><p>${esc(c.terms||'Terms review is required before publication.')}</p><span class="voting-review-date">${c.reviewed?'Administrator reviewed':'Review needed'}${c.checkedAt?' · '+esc(date(c.checkedAt)):''} · ${esc(c.status)}</span><div class="voting-source-links"><a href="${esc(c.source)}" target="_blank" rel="noopener noreferrer">Offering ↗</a>${c.documents?`<a href="${esc(c.documents)}" target="_blank" rel="noopener noreferrer">Documents ↗</a>`:''}</div>${result?`<div class="voting-result"><span>${result.percent.toFixed(1)}% · ${esc(amount(result.weight,p))} ${p.rule==='one-wallet'?'votes':'voting tokens'}</span><div class="voting-result-track"><span style="width:${result.percent}%"></span></div></div>`:''}</div><div class="community-company-actions"><button class="preference-button" data-shared-vote="${c.id}" ${!open||busy||!session?.signedIn||chosen?'disabled':''}>${chosen?'Your current vote':open?(wallet()?(mine?'Change vote':'Sign vote'):'Connect wallet'):r.status==='closed'?'Final results':r.status==='draft'?'Draft only':'Voting unavailable'}</button></div></article>`;}).join('');
}
async function refresh(){
 const seq=++loadSequence;try{
  const [s,list]=await Promise.all([api('session'),api('rounds')]);if(seq!==loadSequence)return;session=s;rounds=list.rounds;
  const requested=location.hash.startsWith('#community/')?location.hash.slice(11):selected?.id;
  const r=rounds.find(r=>r.id===requested)||rounds.find(r=>!['draft','archived','closed','paused'].includes(r.status))||rounds[0];
  let error=null;if(r){const detail=await api('rounds/'+r.id+(wallet()?'?wallet='+encodeURIComponent(wallet()):''));if(seq!==loadSequence)return;selected=detail.round;rounds=rounds.map(item=>item.id===selected.id?selected:item);error=detail.snapshotError;}else selected=null;
  $('#voting-connection').textContent=statusText();$('#rounds-connection').textContent=statusText();renderList();renderRound(error);
 }catch(error){if(seq!==loadSequence)return;$('#voting-connection').textContent='Shared voting unavailable';$('#rounds-connection').textContent='Shared voting unavailable';feedback((session?'The displayed data could not be refreshed. ':'')+error.message);document.querySelectorAll('[data-shared-vote]').forEach(button=>button.disabled=true);if(!session){$('#voting-empty').hidden=false;$('#voting-empty').innerHTML='<h2>Could not load shared rounds</h2><p>Use Refresh to try again. Unavailable results are not counted as zero.</p>';}}
}
const localDate=value=>{if(!value)return '';const d=new Date(value*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const epoch=value=>value?Math.floor(new Date(value).getTime()/1000):0;
async function editRound(id=null){
 try{editing=id?(await api('rounds/'+id)).round:null;requestId=crypto.randomUUID();const p=editing?.payload;
 $('#round-editor-title').textContent=editing?'Edit round draft':'Create a round';$('#round-name').value=p?.title||'';$('#round-notes').value=p?.notes||'';$('#round-target').value=p?.target||'';$('#round-opens').value=localDate(p?.opensAt);$('#round-closes').value=localDate(p?.closesAt);$('#round-chain').value=p?.chainId||4663;$('#round-token').value=p?.token||'';$('#round-rule').value=p?.rule||'';$('#round-minimum').value=p?.minimum||'1';$('#round-form-error').textContent='';
 $('#round-candidate-picker').innerHTML=companies.map(c=>{const saved=p?.candidates.find(v=>v.id===c.id);return `<div class="offering-review"><label class="round-candidate-option"><input type="checkbox" name="candidate" value="${c.id}" ${saved?'checked':''}>${avatar(c)}<span><strong>${esc(c.name)}</strong><small>${esc(c.platform)}</small></span></label><div class="offering-review-fields" ${saved?'':'hidden'}><label>Security / instrument<input data-review="security" value="${esc(saved?.security||c.security)}" maxlength="200"></label><label>Current terms summary<textarea data-review="terms" rows="2" maxlength="2000">${esc(saved?.terms||c.termsNote||'')}</textarea></label><label>Official offering URL<input type="url" data-review="source" value="${esc(saved?.source||c.source)}"></label><label>Official document URL<input type="url" data-review="documents" value="${esc(saved?.documents||c.documents||'')}"></label><label>Current availability<select data-review="status"><option value="unverified">Needs verification</option><option value="open">Open offering</option><option value="secondary">Secondary trading</option><option value="closed">Closed</option></select></label><a href="${esc(c.source)}" target="_blank" rel="noopener noreferrer" class="round-text-link">Open source to review ↗</a><label class="offering-review-confirm"><input type="checkbox" data-review="reviewed" ${saved?.reviewed?'checked':''} data-checked-at="${saved?.checkedAt||0}">I reviewed the current offering and documents.</label><small>Record only terms you have checked. Material changes require a new revision after publication.</small></div></div>`;}).join('');
 for(const c of p?.candidates||[]){const row=$(`#round-candidate-picker [name=candidate][value="${c.id}"]`).closest('.offering-review');row.querySelector('[data-review=status]').value=c.status;}
 updatePicker();$('#round-editor').showModal();$('#round-name').focus();
 }catch(error){feedback(error.message);}
}
function updatePicker(){$('#round-candidate-selection').textContent=`${document.querySelectorAll('#round-candidate-picker [name=candidate]:checked').length} selected · 2–12` ;}
$('#round-candidate-picker').addEventListener('change',event=>{const row=event.target.closest('.offering-review');if(!row)return;if(event.target.matches('[name=candidate]')){row.querySelector('.offering-review-fields').hidden=!event.target.checked;updatePicker();}if(event.target.matches('[data-review=reviewed]'))event.target.dataset.checkedAt=event.target.checked?String(Math.floor(Date.now()/1000)):'0';else if(event.target.matches('[data-review]')){const reviewed=row.querySelector('[data-review=reviewed]');reviewed.checked=false;reviewed.dataset.checkedAt='0';}});
$('#round-form').addEventListener('submit',async event=>{
 event.preventDefault();const submit=event.submitter||$('#round-form button[type=submit]');submit.disabled=true;$('#round-form-error').textContent='';
 try{const candidates=[...document.querySelectorAll('#round-candidate-picker [name=candidate]:checked')].map(input=>{const row=input.closest('.offering-review'),value=field=>row.querySelector(`[data-review=${field}]`);return {id:input.value,security:value('security').value,terms:value('terms').value,source:value('source').value,documents:value('documents').value,status:value('status').value,reviewed:value('reviewed').checked,checkedAt:Number(value('reviewed').dataset.checkedAt||0)};});
 const input={requestId,title:$('#round-name').value,notes:$('#round-notes').value,target:$('#round-target').value,opensAt:epoch($('#round-opens').value),closesAt:epoch($('#round-closes').value),chainId:Number($('#round-chain').value),token:$('#round-token').value,rule:$('#round-rule').value,minimum:$('#round-minimum').value,candidates,version:editing?.version};
 const result=await api(editing?'rounds/'+editing.id:'rounds',input,editing?'PUT':'POST');selected=result.round;$('#round-editor').close();filter='all';await refresh();feedback('Draft saved to shared storage. It has not been published.');
 }catch(error){$('#round-form-error').textContent=error.message;}finally{submit.disabled=false;}
});
async function openAction(id,action){
 try{const r=(await api('rounds/'+id)).round;actionPending={id,action,version:r.version};$('#round-action-error').textContent='';$('#round-action-reason').value='';$('#round-action-reason-label').hidden=!['pause','revise'].includes(action);
 const title={publish:'Publish this round?',pause:'Pause voting',revise:'Create a new revision',archive:r.status==='archived'?'Restore draft':'Archive draft'}[action];$('#round-action-title').textContent=title;$('#confirm-round-action').textContent={publish:'Publish round',pause:'Pause voting',revise:'Create revision',archive:r.status==='archived'?'Restore':'Archive'}[action];
 $('#round-action-copy').innerHTML=`<p>${esc(r.payload.title)} · revision ${r.revision}</p><p class="community-footnote">${action==='publish'?'Publishing freezes the shortlist, reviewed terms, token and voting rules. The server verifies token support. Voting opens '+esc(date(r.payload.opensAt))+' and closes '+esc(date(r.payload.closesAt))+'.':action==='revise'?'The current round will stop accepting votes. Its ballots remain in history. The new draft requires a fresh review and fresh votes.':action==='pause'?'Keep the ballot history and stop further voting. Publish a new revision to restart.':'This changes an unpublished draft only.'}</p>`;$('#round-action-dialog').showModal();
 }catch(error){feedback(error.message);}
}
$('#confirm-round-action').addEventListener('click',async()=>{if(!actionPending)return;const button=$('#confirm-round-action');button.disabled=true;try{const {id,action,version}=actionPending;const result=await api(`rounds/${id}/${action}`,{version,reason:$('#round-action-reason').value});selected=result.round;$('#round-action-dialog').close();await refresh();feedback('Round updated in shared storage.');if(action==='revise')await editRound(result.round.id);}catch(error){$('#round-action-error').textContent=error.message;}finally{button.disabled=false;}});
async function castVote(candidate){
 if(busy)return;if(!wallet()){$('#wallet-button').click();return;}busy=true;renderRound();feedback('Verifying your token holding at the opening snapshot…');
 try{const r=selected,account=wallet(),challenge=await api(`rounds/${r.id}/challenge`,{wallet:account,candidate});if(wallet()?.toLowerCase()!==account.toLowerCase())throw Error('The wallet changed. Start the vote again.');feedback('Review and sign the ballot in your wallet. No funds will move.');const signature=await window.CapitalWallet.signBallot(challenge.typedData);if(wallet()?.toLowerCase()!==account.toLowerCase())throw Error('The wallet changed before submission. Start the vote again.');feedback('Checking your signature and recording the ballot…');const accepted=await api(`rounds/${r.id}/ballot`,{challengeId:challenge.challengeId,signature});await refresh();feedback(`Vote accepted for ${r.payload.title} · receipt ${accepted.receipt.id} · ${date(accepted.receipt.acceptedAt)}. You can replace your choice before voting closes.`);
 }catch(error){feedback(error.code===4001||error.code==='ACTION_REJECTED'?'Signing was cancelled. No new vote was submitted.':error.message);}finally{busy=false;renderRound();}
}
async function auditPage(id,append=false){try{auditRound=id;if(!append){auditOffset=0;$('#round-audit-content').innerHTML='<p>Loading verified ballot history…</p>';$('#round-audit-dialog').showModal();}const result=await api(`rounds/${id}/audit?offset=${auditOffset}`);if(!append)$('#round-audit-content').innerHTML=`<p class="community-footnote">Each receipt keeps the signed message. A newer ballot replaces that wallet’s earlier choice in totals; earlier receipts remain here.</p><div class="round-audit-events">${result.events.map(e=>`<p><strong>${esc(e.action.replaceAll('-',' '))}</strong> · ${esc(date(e.created_at))}${e.detail.reason?'<br>'+esc(e.detail.reason):''}</p>`).join('')}</div>`;$('#round-audit-content').insertAdjacentHTML('beforeend',result.receipts.length?result.receipts.map(v=>`<details class="voting-receipt"><summary>${esc(companies.find(c=>c.id===v.candidate)?.name||v.candidate)} · ballot ${v.sequence}<small>${esc(v.wallet)} · ${esc(date(v.accepted_at))}</small></summary><pre>${esc(JSON.stringify(v,null,2))}</pre></details>`).join(''):'<p class="community-footnote">No signed ballots have been accepted.</p>');auditOffset=result.nextOffset;$('#round-audit-more').hidden=!result.hasMore;}catch(error){$('#round-audit-content').textContent=error.message;}}
$('#new-round').addEventListener('click',()=>editRound());$('#refresh-voting').addEventListener('click',refresh);$('#community-round').addEventListener('change',event=>{location.hash='community/'+event.target.value;});$('#open-round-audit').addEventListener('click',()=>auditPage(selected.id));$('#round-audit-more').addEventListener('click',()=>auditPage(auditRound,true));
document.addEventListener('click',event=>{const edit=event.target.closest('[data-edit-round]'),action=event.target.closest('[data-round-action]'),vote=event.target.closest('[data-shared-vote]'),f=event.target.closest('[data-round-filter]');if(edit)editRound(edit.dataset.editRound);if(action)openAction(action.dataset.roundId,action.dataset.roundAction);if(vote)castVote(vote.dataset.sharedVote);if(f){filter=f.dataset.roundFilter;renderList();}});
window.addEventListener('hashchange',()=>{if(/^#(community|rounds)(\/|$)/.test(location.hash))refresh();});document.addEventListener('mainstreet:wallet',()=>{if(selected)renderRound();if(session)refresh();});
setInterval(()=>{if(!document.hidden&&!busy&&!document.querySelector('dialog[open]')&&/^#(community|rounds)(\/|$)/.test(location.hash))refresh();},30000);
refresh();

function legacyDrafts(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?validateState(JSON.parse(raw),companies.map(c=>c.id)).rounds:[];}catch{return [];}}
const importButton=document.createElement('button');importButton.id='import-browser-drafts';importButton.className='round-text-link';importButton.textContent='Import browser drafts';importButton.hidden=true;$('#rounds-connection').after(importButton);
importButton.addEventListener('click',async()=>{importButton.disabled=true;let count=0;try{for(const draft of legacyDrafts()){
 const hex=textHash('capital-draft-import:'+location.origin+':'+draft.id).slice(2,34),requestId=[hex.slice(0,8),hex.slice(8,12),hex.slice(12,16),hex.slice(16,20),hex.slice(20)].join('-');
 await api('rounds',{requestId,title:draft.title,notes:draft.notes,target:draft.target,chainId:4663,token:'',rule:'',minimum:'1',opensAt:0,closesAt:0,candidates:draft.candidates.map(id=>{const c=companies.find(c=>c.id===id);return {id,security:c.security,source:c.source,documents:c.documents||'',terms:c.termsNote||'',status:'unverified',reviewed:false,checkedAt:0};})});count++;}
 await refresh();feedback(count+' browser drafts imported into shared storage. Browser preferences were not submitted as votes.');}catch(error){feedback(count+' drafts imported. '+error.message);}finally{importButton.disabled=false;}});
if(document.modelContext?.registerTool){
 const context=document.modelContext;const emptyInput=input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('This tool does not accept parameters.');};
 for(const tool of [
 {name:'capital_read_voting_rounds',title:'Read Capital voting rounds',description:'Refresh and read shared round status and accepted ballot totals. Does not cast a vote.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{emptyInput(input);await refresh();if($('#voting-connection').textContent==='Shared voting unavailable')throw Error('Shared voting unavailable');return {rounds:rounds.map(r=>({id:r.id,title:r.payload.title,status:r.status,revision:r.revision,acceptedBallots:r.results?.wallets??null}))};}},
 {name:'capital_start_round_draft',title:'Open a round draft',description:'Open the administrator draft editor. This does not save or publish a round.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{emptyInput(input);if(!session?.isAdmin)throw Error('Administrator access required');await editRound();if(!$('#round-editor').open)throw Error('The editor could not be opened');return {status:'editor-open',saved:false,published:false};}}
 ]){try{Promise.resolve(context.registerTool(tool)).catch(()=>{});}catch{}}
}
